# Generated by Django 5.1.3 on 2024-11-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maquinas', '0003_alter_marcador_latitud_alter_marcador_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('camara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maquinas.camara')),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='Planos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Marcador',
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
        migrations.AddField(
            model_name='camara',
            name='piso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maquinas.piso'),
        ),
    ]
